apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pcb-resolution-control-final-workspace
  namespace: csuf-titans
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: rook-ceph-block-fullerton
  resources:
    requests:
      storage: 100Gi
