apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pcb-rtdetr-highres-resume-workspace
  namespace: csuf-titans
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: rook-ceph-block-fullerton
  resources:
    requests:
      storage: 30Gi
  dataSource:
    apiGroup: ""
    kind: PersistentVolumeClaim
    name: pcb-rtdetr-highres-workspace
