apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pcb-publication-workspace
  namespace: csuf-titans
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: rook-ceph-block
